# Generated by Django 3.0.1 on 2019-12-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Description about the part functionalities",
                        max_length=255,
                        verbose_name="description",
                    ),
                ),
                (
                    "stock_qty_min",
                    models.IntegerField(
                        default=0,
                        help_text="How many do you needs to have at minimum ?",
                        verbose_name="minimum stock quantity",
                    ),
                ),
                (
                    "stock_qty",
                    models.IntegerField(
                        default=1, help_text="How many do you have now ?", verbose_name="stock quantity"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True, help_text="Comments about the part itself", max_length=255, verbose_name="comment"
                    ),
                ),
                (
                    "production_remarks",
                    models.CharField(
                        blank=True, help_text="Production remarks", max_length=255, verbose_name="production remarks"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        help_text="Notes about some parts conditions ?",
                        max_length=255,
                        verbose_name="condition",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False, help_text="Does this part notice needs review ?", verbose_name="needs review"
                    ),
                ),
                (
                    "can_be_sold",
                    models.BooleanField(
                        default=False, help_text="Are you willing to sold some parts ?", verbose_name="can be sold"
                    ),
                ),
                (
                    "private",
                    models.BooleanField(default=False, help_text="Oh no it's a private part !", verbose_name="private"),
                ),
                (
                    "internal_part_number",
                    models.CharField(
                        blank=True,
                        help_text="Internal part number",
                        max_length=255,
                        verbose_name="internal part number",
                    ),
                ),
            ],
            options={"verbose_name": "part", "verbose_name_plural": "parts", "ordering": ("name",)},
        )
    ]
