# Generated by Django 3.0.1 on 2019-12-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("part", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="part",
            name="status",
            field=models.CharField(
                blank=True, help_text="Notes about the inventory sheet status ?", max_length=255, verbose_name="status"
            ),
        )
    ]
