# Generated by Django 3.0.1 on 2019-12-28 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("part", "0002_part_status")]

    operations = [
        migrations.CreateModel(
            name="PartUnit",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="ex. Centimeters", max_length=255, unique=True, verbose_name="name"),
                ),
                ("short_name", models.CharField(help_text="ex. cms", max_length=255, verbose_name="short name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
            ],
            options={"verbose_name": "part unit", "verbose_name_plural": "part units", "ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="part",
            name="part_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="part.PartUnit"
            ),
        ),
    ]
