# Generated by Django 3.0.1 on 2019-12-28 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("footprints", "0001_initial"), ("part", "0003_auto_20191228_1307")]

    operations = [
        migrations.AddField(
            model_name="part",
            name="footprint",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="footprints.Footprint"
            ),
        )
    ]
