# Generated by Django 3.0.1 on 2019-12-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('part', '0004_part_footprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.Category'),
        ),
    ]
