# Generated by Django 3.0.1 on 2019-12-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        ("part", "0005_part_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="storage",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="storage.StorageLocation"
            ),
        ),
    ]
