# Generated by Django 3.0.1 on 2019-12-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0008_partattachment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="part", options={"ordering": ("category",), "verbose_name": "part", "verbose_name_plural": "parts"},
        ),
    ]
