# Generated by Django 3.0.1 on 2019-12-30 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0011_auto_20191230_1310"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partparameter",
            options={"ordering": ("name",), "verbose_name": "Part parameter", "verbose_name_plural": "Part parameters"},
        ),
        migrations.AddField(
            model_name="part",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
