# Generated by Django 3.1.2 on 2020-11-04 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0013_auto_20200104_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="part_unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="part.partunit"
            ),
        ),
        migrations.AlterField(
            model_name="partparameter",
            name="unit",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="part.parametersunit"
            ),
        ),
    ]
