# Generated by Django 3.1.3 on 2020-11-12 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20191228_1507"),
        ("part", "0014_auto_20201104_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="categories.category"
            ),
        ),
    ]
