# Generated by Django 3.1.3 on 2020-11-15 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0015_auto_20201112_2218"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
