# Generated by Django 3.1.3 on 2020-11-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0016_auto_20201115_1418"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartStockHistory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("diff", models.IntegerField(verbose_name="difference")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="part_stock_history", to="part.part"
                    ),
                ),
            ],
            options={
                "verbose_name": "Part stock history",
                "verbose_name_plural": "Part stock history",
                "ordering": ("created_at",),
            },
        ),
    ]
