# Generated by Django 3.1.3 on 2020-11-18 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0017_partstockhistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partstockhistory",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Part stock history",
                "verbose_name_plural": "Part stock history",
            },
        ),
    ]
