# Generated by Django 3.2.2 on 2021-05-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0018_auto_20201118_1139"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartParameterPreset",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
            ],
        ),
        migrations.CreateModel(
            name="PartParameterPresetItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
                (
                    "part_parameter_preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_parameter_presets_value",
                        to="part.partparameterpreset",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="part.parametersunit"
                    ),
                ),
            ],
        ),
    ]
