# Generated by Django 3.2.2 on 2021-05-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0019_partparameterpreset_partparameterpresetitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partparameterpresetitem",
            name="part_parameter_preset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="part_parameters_presets",
                to="part.partparameterpreset",
            ),
        ),
    ]
