# Generated by Django 3.2.2 on 2021-05-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0021_dedup_parametersunit_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parametersunit",
            name="prefix",
        ),
    ]
