# Generated by Django 3.2.2 on 2021-05-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0022_remove_parametersunit_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parametersunit",
            name="name",
            field=models.CharField(help_text="ex. Ampere", max_length=255, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="parametersunit",
            name="symbol",
            field=models.CharField(blank=True, help_text="ex. A", max_length=255, unique=True, verbose_name="symbol"),
        ),
    ]
