# Generated by Django 4.0.2 on 2022-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0023_auto_20210509_1337"),
    ]

    operations = [
        migrations.AddField(
            model_name="partattachment",
            name="file_size",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="partattachment",
            name="file_type",
            field=models.CharField(default="un/known", max_length=200),
            preserve_default=False,
        ),
    ]
