# Generated by Django 4.1.1 on 2022-10-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_alter_storage_uuid_alter_storagecategory_uuid"),
        ("part", "0027_alter_partparameterpreset_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="new_storage",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="storage.storage"
            ),
        ),
    ]
