# Generated by Django 4.1.1 on 2022-10-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0029_auto_20221011_1830"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="part",
            name="storage",
        ),
    ]
