# Generated by Django 4.1.1 on 2022-10-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0030_remove_part_storage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="new_storage",
            new_name="storage",
        ),
    ]
