# Generated by Django 3.0.1 on 2020-01-01 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0005_auto_20200101_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturerlogo",
            name="manufacturer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logos",
                to="manufacturer.Manufacturer",
            ),
            preserve_default=False,
        ),
    ]
