# Generated by Django 3.1.3 on 2020-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0006_auto_20200101_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="address",
            field=models.TextField(blank=True, help_text="Address", verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="comment",
            field=models.TextField(blank=True, help_text="Comment", verbose_name="comment"),
        ),
    ]
