# Generated by Django 3.1.3 on 2020-11-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0007_auto_20201114_1635"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partmanufacturer",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts_manufacturers_sku",
                to="manufacturer.manufacturer",
            ),
        ),
    ]
