# Generated by Django 3.1.3 on 2020-11-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0010_auto_20201114_1843"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManufacturerLogo",
        ),
    ]
