# Generated by Django 3.1.3 on 2020-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0011_delete_manufacturerlogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturer",
            name="datasheet_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Datasheet URL"),
        ),
        migrations.AddField(
            model_name="partmanufacturer",
            name="datasheet_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Datasheet URL"),
        ),
    ]
