# Generated by Django 4.1.1 on 2022-10-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0012_auto_20201205_0637"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerAlias",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alias", models.CharField(max_length=255, verbose_name="alias")),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_manufacturers_alias",
                        to="manufacturer.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturer alias",
                "verbose_name_plural": "Manufacturers aliases",
                "ordering": ("alias",),
            },
        ),
    ]
