# Generated by Django 4.1.1 on 2022-10-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0013_manufactureralias"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManufacturerAlias",
        ),
    ]
