# Generated by Django 5.1.4 on 2024-12-23 10:48

import oauth2_provider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0006_alter_application_client_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(db_index=True, default=None, max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="allowed_origins",
            field=models.TextField(
                blank=True, default="", help_text="Allowed origins list to enable CORS, space separated"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="hash_client_secret",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="application",
            name="post_logout_redirect_uris",
            field=models.TextField(blank=True, default="", help_text="Allowed Post Logout URIs list, space separated"),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="token_family",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.TextField(),
        ),
    ]
