# Generated by Django 3.0.1 on 2019-12-28 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FootprintCategory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="ex. PDIP", max_length=255, unique=True, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
            ],
            options={
                "verbose_name": "footprint category",
                "verbose_name_plural": "footprint categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Footprint",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="ex. PBGA-260", max_length=64, unique=True, verbose_name="name")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="description")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        help_text="Footprint schematic",
                        null=True,
                        upload_to="footprints/",
                        verbose_name="Footprint picture",
                    ),
                ),
                (
                    "footprint",
                    models.ForeignKey(
                        help_text="Main category of the footprint",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="footprints.FootprintCategory",
                        verbose_name="Footprint",
                    ),
                ),
            ],
            options={"verbose_name": "footprint", "verbose_name_plural": "footprints", "ordering": ("name",)},
        ),
    ]
