# Generated by Django 4.1.1 on 2022-09-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("footprints", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="footprint",
            old_name="footprint",
            new_name="category",
        ),
    ]
