# Generated by Django 4.1.1 on 2022-09-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("footprints", "0002_rename_footprint_footprint_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footprint",
            name="category",
            field=models.ForeignKey(
                help_text="Category of the footprint",
                on_delete=django.db.models.deletion.CASCADE,
                to="footprints.footprintcategory",
                verbose_name="Category",
            ),
        ),
    ]
