# Generated by Django 3.0.1 on 2019-12-30 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0002_auto_20191229_1515"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
