# Generated by Django 3.0.1 on 2020-01-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0004_auto_20200101_1736"),
    ]

    operations = [
        migrations.AddField(
            model_name="storagelocation",
            name="description",
            field=models.CharField(blank=True, max_length=255, verbose_name="description"),
        ),
    ]
