# Generated by Django 4.1.1 on 2022-10-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0010_alter_storage_uuid_alter_storagecategory_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storagelocation",
            name="category",
        ),
        migrations.DeleteModel(
            name="StorageCategory",
        ),
        migrations.DeleteModel(
            name="StorageLocation",
        ),
    ]
