# .tmuxinator.yml

name: dev
root: .

tmux_command: sleep 1 && tmux

windows:
  - servers:
      layout: main-vertical
      panes:
        - backend:
            - export DJANGO_SETTINGS_MODULE=config.settings.local
            - export DEBUG_TOOLBAR_ENABLED=False
            - source venv/bin/activate.fish
            - cd api
            - python3 manage.py runserver 0.0.0.0:8000
        - frontend:
            - cd front
            - VUE_APP_SERVER_URL=http://127.0.0.1:8000 yarn dev

