FROM node:23.5.0-alpine as builder-front

RUN apk add --update --no-cache yarn python3 make gcc g++ \
    && rm -rf /var/cache/apk/*

ADD ./front/ /front/

ENV NODE_OPTIONS=--openssl-legacy-provider

RUN \
    echo 'building frontend' && \
    cd /front/ && \
    yarn install && \
    yarn build

FROM alpine:3.21 as builder-backend

RUN \
    echo 'installing dependencies' && \
    apk add --no-cache \
    bash \
    git \
    musl-dev \
    gcc \
    rust cargo \
    libffi libffi-dev \
    postgresql-dev \
    python3-dev \
    python3 \
    py3-pip \
    py3-psycopg2 \
    py3-virtualenv \
    make \
    zlib-dev \
    jpeg-dev \
    libmagic

ADD ./api/ /app/api/
ADD ./setup-data/ /app/setup-data/

# hack around https://github.com/pypa/pip/issues/6158#issuecomment-456619072
ENV PIP_DOWNLOAD_CACHE=/noop/
RUN \
    echo 'installing pip requirements' && \
    python -m virtualenv /venv && \
    /venv/bin/pip install --upgrade pip && \
    /venv/bin/pip install setuptools wheel && \
    /venv/bin/pip install -r /app/api/requirements.txt && \
    rm -rf $PIP_DOWNLOAD_CACHE

COPY --from=builder-front /front/dist /app/front

RUN mkdir /uploads /statics
VOLUME /uploads
VOLUME /statics

EXPOSE 8000
WORKDIR /app/api/
ENTRYPOINT ["./docker/entrypoint.sh"]
CMD ["./docker/server.sh"]
