name: stockazio
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-allinone
    volumes:
      - ./uploads:/uploads
    env_file:
      - env.prod
    ports:
      - 8081:8000
    restart: always