# Generated by Django 3.0.1 on 2019-12-28 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("part", "0007_parametersunit_partparameter"),
        ("distributor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorSku",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sku", models.CharField(max_length=255, verbose_name="sku id")),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parts_distributors_sku",
                        to="distributor.Distributor",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distributors_sku",
                        to="part.Part",
                    ),
                ),
            ],
            options={"verbose_name": "Distributor", "verbose_name_plural": "Distributors", "ordering": ("sku",),},
        ),
    ]
