# Generated by Django 3.1.3 on 2020-11-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributor", "0004_auto_20201104_0943"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distributor",
            name="address",
            field=models.TextField(blank=True, help_text="Address", verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="comment",
            field=models.TextField(blank=True, help_text="Comment", verbose_name="comment"),
        ),
    ]
