# Generated by Django 3.0.1 on 2019-12-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="category", unique_together=set(),),
        migrations.RemoveField(model_name="category", name="slug",),
    ]
