# Generated by Django 4.1.1 on 2022-10-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_remove_category_level_remove_category_lft_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
    ]
