# Generated by Django 3.1.3 on 2020-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_auto_20201118_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectpart",
            name="sourced",
            field=models.BooleanField(default=False, verbose_name="sourced"),
        ),
    ]
