# Generated by Django 3.2.2 on 2021-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20201119_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state_notes',
            field=models.TextField(blank=True, max_length=255, verbose_name='state notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(1, 'Planned'), (2, 'Ongoing'), (3, 'Finished'), (4, 'On-hold'), (5, 'Abandonned'), (99, 'Unknown')], default=99, verbose_name='state'),
        ),
    ]
