# Generated by Django 3.1.2 on 2020-11-04 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(verbose_name="date")),
                ("order_number", models.CharField(max_length=255, unique=True, verbose_name="order number")),
                ("status", models.CharField(default="UNKNOWN", max_length=20, verbose_name="status of order")),
                ("vendor", models.CharField(default="unknown", max_length=255, verbose_name="vendor")),
                ("import_state", models.IntegerField(default=0, verbose_name="import state")),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("vendor_part_number", models.CharField(max_length=255, verbose_name="vendor part number")),
                ("mfr_part_number", models.CharField(max_length=255, verbose_name="manufacturer part number")),
                ("manufacturer", models.CharField(max_length=255, verbose_name="manufacturer")),
                ("description", models.CharField(max_length=255, verbose_name="description")),
                ("quantity", models.IntegerField(default=0, verbose_name="quantity")),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="OrdersImporter.order")),
            ],
        ),
    ]
