# Generated by Django 3.1.2 on 2020-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrdersImporter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="order",
            name="import_state",
            field=models.IntegerField(
                choices=[(0, "Unknown"), (1, "Fetched"), (2, "Imported"), (99, "Error")],
                default=0,
                verbose_name="import state",
            ),
        ),
    ]
