# Generated by Django 3.1.2 on 2020-11-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20191228_1507"),
        ("OrdersImporter", "0002_auto_20201104_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="categories.category"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="ignore",
            field=models.BooleanField(default=False, verbose_name="ignore import"),
        ),
    ]
