# Generated by Django 3.1.2 on 2020-11-05 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_auto_20191228_1507"),
        ("OrdersImporter", "0003_auto_20201104_1547"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMatcher",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("regexp", models.CharField(max_length=255, verbose_name="regexp")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="categories.category"
                    ),
                ),
            ],
        ),
    ]
