# Generated by Django 3.1.2 on 2020-11-05 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturer", "0006_auto_20200101_1744"),
        ("distributor", "0004_auto_20201104_0943"),
        ("OrdersImporter", "0004_categorymatcher"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="manufacturer_db",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="manufacturer.manufacturer"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="vendor_db",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="distributor.distributor"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="OrdersImporter.order"
            ),
        ),
    ]
