# Generated by Django 3.1.3 on 2020-11-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OrdersImporter", "0005_auto_20201105_1806"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-date"]},
        ),
    ]
