# Generated by Django 5.1.4 on 2024-12-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrdersImporter", "0006_auto_20201114_1602"),
        ("footprints", "0003_alter_footprint_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="footprint_db",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="footprints.footprint"
            ),
        ),
    ]
