# Generated by Django 5.1.4 on 2024-12-28 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OrdersImporter", "0007_item_footprint_db"),
        ("part", "0031_rename_new_storage_part_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="new_in_stock",
            field=models.BooleanField(default=False, verbose_name="new part in stock"),
        ),
        migrations.AddField(
            model_name="item",
            name="part_db",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="part.part"
            ),
        ),
    ]
