# Generated by Django 4.0.2 on 2022-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("width", models.IntegerField(default=90)),
                ("height", models.IntegerField(default=38)),
                ("basePdf", models.TextField()),
                ("template", models.TextField()),
            ],
        ),
    ]
