# Generated by Django 4.0.2 on 2022-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeltemplate", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="labeltemplate",
            name="basePdf",
        ),
        migrations.AddField(
            model_name="labeltemplate",
            name="base_pdf",
            field=models.TextField(default="lol", editable=False),
            preserve_default=False,
        ),
    ]
