# Generated by Django 4.0.2 on 2022-02-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeltemplate", "0003_labeltemplate_text_template_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labeltemplate",
            name="text_template",
            field=models.TextField(default="{name}\n{description}"),
        ),
    ]
