# Generated by Django 5.1.4 on 2024-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labeltemplate", "0004_alter_labeltemplate_text_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeltemplate",
            name="default",
            field=models.BooleanField(default=False),
        ),
    ]
